[package]
name = "justice_review_artifact_linux"
version = "0.1.0"
edition = "2021"
publish = false

[features]
test = ["napi/noop"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "=0.2.177"
napi = { version = "=3.12.2", default-features = false, features = ["napi8"] }
napi-derive = "=3.6.8"

[build-dependencies]
napi-build = "=2.4.1"
