name: Semgrep

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --config=auto --sarif --output semgrep.sarif
      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
